# Site settings
title: "BioVis 2025"
email: "website@biovis.net"
description: "Biological Data Visualization"
baseurl: "/2025"
url: "http://biovis.net"
conferenceshort: "BioVis 2025"

IEEE_conference_date: "November 2 - 7, 2025"
IEEE_conference_place: "Vienna, Austria"
IEEE_challenge_date: "TBA"

year: 2025

# Old deadlines so I remember what they're called
# When everything breaks
IEEE_deadline_submission: "TBA"
IEEE_deadline_notification: "TBA"
IEEE_deadline_camera: "TBA"

ismb_conference_name: "ISMB/ECCB 2025"
ismb_conference_link: "https://www.iscb.org/ismbeccb2025"
ismb_conference_registration_link: "https://www.iscb.org/ismbeccb2025/register"
ismb_conference_date: "July 20 - 25, 2025"
ismb_conference_place: "Liverpool, UK - ACC Liverpool"
ismb_conference_key_dates_link: "https://www.iscb.org/ismbeccb2025/key-dates"

ismb_cosi_date: "July 24, 2025"

ismb_paper_submission_deadline: "January 23, 2025"
ismb_paper_conditional_acceptance: "March 13, 2025"
ismb_paper_revision_deadline: "March 27, 2025"
ismb_paper_final_acceptance: "April 2, 2025"

ismb_talk_submission_deadline: "April 17, 2025"
ismb_talk_acceptance: "May 13, 2025"

ismb_poster_submission_deadline: "April 17, 2025"
ismb_poster_acceptance: "May 13, 2025"
ismb_poster_late_submission_deadline: "May 15, 2025"
ismb_poster_late_acceptance: "May 22, 2025"

ismb_paper_submission_link: "https://www.iscb.org/ismbeccb2025/call-for-submissions/proceedings"
ismb_abstract_submission_link: "https://www.iscb.org/ismbeccb2025/call-for-submissions/abstracts"

#bmc_submission_deadline: ""
#bmc_conditional_accept: ""
#bmc_final_accpet: ""

# Build settings
markdown: kramdown

collections:
    - posters_ISMB

google_analytics: "'UA-22015250-1'"
use_analytics: false
encoding: utf-8
lang: en-US
